Repository telekom/pixelshades, pull requests merged in 2024-05, with the labels that each got.

#63 feat(docs): extend docs
  apps/docs/content/components/dialog.mdx
  apps/docs/content/components/form.mdx
  apps/docs/content/components/heading.mdx
  apps/docs/content/components/loading-spinner.mdx
  apps/docs/content/components/loadingSpinner.mdx
  apps/docs/content/components/menu.mdx
  apps/docs/content/components/popover.mdx
  apps/docs/content/components/progress-bar.mdx
  apps/docs/content/components/radio-group.mdx
  apps/docs/content/components/select.mdx
  apps/docs/content/components/separator.mdx
  apps/docs/content/components/table.mdx
  apps/docs/content/components/tabs.mdx
  apps/docs/src/components/copy-button.tsx
  apps/docs/src/components/props-table.tsx
  apps/docs/src/examples/heading/flat-heading-levels.tsx
  apps/docs/src/examples/heading/nested-heading-level.tsx
  apps/docs/src/examples/heading/preview.tsx
  apps/docs/src/examples/index.ts
  apps/docs/src/examples/link/sizes.tsx
  apps/docs/src/examples/loading-spinner/button.tsx
  apps/docs/src/examples/loading-spinner/icons.tsx
  apps/docs/src/examples/loading-spinner/preview.tsx
  apps/docs/src/examples/loading-spinner/sizes.tsx
  apps/docs/src/examples/loading-spinner/variants.tsx
  apps/docs/src/examples/typography/preview.tsx
  apps/docs/src/lib/props.json
  bun.lockb
  packages/ui/package.json
  packages/ui/src/components/ui/heading/heading.tsx
  packages/ui/src/components/ui/highlight/highlight.tsx
  packages/ui/src/components/ui/kbd/kbd.tsx
  packages/ui/src/components/ui/link/link.tsx
  packages/ui/src/components/ui/loading-spinner/loading-spinner.tsx
  packages/ui/src/components/ui/number-field/number-field.tsx
  packages/ui/src/components/ui/progress-bar/progress-bar.tsx
  packages/ui/src/components/ui/radio-group/radio-group.tsx
  packages/ui/src/components/ui/select/select.tsx
  packages/ui/src/components/ui/switch/switch.tsx
  packages/ui/src/components/ui/table/table.tsx
  packages/ui/src/components/ui/text-field/text-field.tsx
  packages/ui/src/components/ui/time-field/time-field.tsx
  packages/ui/src/components/ui/tooltip/tooltip.tsx
  packages/ui/src/components/ui/typography/typography.tsx
Labels: documentation

#90 feat(docs): make sidebar nav items sortable
  apps/docs/content/general/color-system.mdx
  apps/docs/content/general/installation.mdx
  apps/docs/content/general/introduction.mdx
  apps/docs/src/config/docs.ts
  apps/docs/src/routes/docs.tsx
  apps/docs/velite.config.ts
Labels: documentation, enhancement

#93 Feat/avatar
  .changeset/nine-swans-do.md
  apps/docs/content/components/avatar.mdx
  apps/docs/src/examples/avatar/initials.tsx
  apps/docs/src/examples/avatar/preview.tsx
  apps/docs/src/examples/index.ts
  apps/docs/src/index.css
  packages/styles/package.json
  packages/styles/src/components/avatar/index.ts
  packages/styles/src/components/avatar/variants.ts
  packages/ui/src/components/ui/avatar/avatar.tsx
  packages/ui/src/components/ui/avatar/index.ts
  packages/ui/src/components/ui/index.ts
Labels: enhancement
